### ISSUE TITLE
 Graph App 'Neo4j Browser' can't be opened

### ISSUE THREAD

**Issue by luanne** [neo4j/neo4j-browser#1259]
### Description
The Neo4j Browser in Desktop won't open any more, probably after upgrading to MacOS Big Sur

### Reproduce Steps
Start any database, try to open the browser

### Expected Behavior
The browser opens as before

### Current Behavior

Graph App 'Neo4j Browser' can't be opened.

From the logs:

```
[2020-12-29 14:32:43.709] [info] Graph App[3e3b7769-c549-4e8f-8718-2ef62175282b]: Version 0.5.1 satisfied. {
  desktopApiVersion: '1.4.0',
  packageDesktopApiVersion: '>=1.2.x <2.0.0'
}
[2020-12-29 14:32:44.374] [info] Graph App[d3bdb54e-7f71-4b77-ac21-3510670ef757]: Checking 1.5.1 for suitable desktop API version
[2020-12-29 14:32:44.375] [info] Graph App[d3bdb54e-7f71-4b77-ac21-3510670ef757]: Version 1.5.1 satisfied. { desktopApiVersion: '1.4.0', packageDesktopApiVersion: '^1.4.0' }
[2020-12-29 14:32:44.405] [info] Graph App[neo4j-bloom-id]: Checking 1.4.1 for suitable desktop API version
[2020-12-29 14:32:44.405] [info] Graph App[neo4j-bloom-id]: Version 1.4.1 satisfied. { desktopApiVersion: '1.4.0', packageDesktopApiVersion: '^1.4.0' }
[2020-12-29 14:32:44.534] [info] Graph App[neo4j-browser-id]: Checking 4.2.0 for suitable desktop API version
[2020-12-29 14:32:44.534] [info] Graph App[neo4j-browser-id]: Version 4.2.0 satisfied. { desktopApiVersion: '1.4.0', packageDesktopApiVersion: '^1.4.0' }
[2020-12-29 14:32:45.690] [info] Checking ports
[2020-12-29 14:32:45.705] [info] Starting Neo4j
[2020-12-29 14:32:45.705] [info] Starting db [database-8922ec47-87cf-41ea-b1b0-2e87329e69ef] 'v4.0.8'
[2020-12-29 14:32:46.033] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7687 }
[2020-12-29 14:32:46.034] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7474 }
[2020-12-29 14:32:46.035] [info] Neo4j @ 7687 is down. connect ECONNREFUSED 127.0.0.1:7687
[2020-12-29 14:32:46.036] [info] Neo4j @ 7474 is down. connect ECONNREFUSED 127.0.0.1:7474
[2020-12-29 14:32:47.136] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7687 }
[2020-12-29 14:32:47.137] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7474 }
[2020-12-29 14:32:47.138] [info] Neo4j @ 7687 is down. connect ECONNREFUSED 127.0.0.1:7687
[2020-12-29 14:32:47.138] [info] Neo4j @ 7474 is down. connect ECONNREFUSED 127.0.0.1:7474
[2020-12-29 14:32:48.231] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7687 }
[2020-12-29 14:32:48.232] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7474 }
[2020-12-29 14:32:48.233] [info] Neo4j @ 7687 is down. connect ECONNREFUSED 127.0.0.1:7687
[2020-12-29 14:32:48.233] [info] Neo4j @ 7474 is down. connect ECONNREFUSED 127.0.0.1:7474
[2020-12-29 14:32:49.332] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7687 }
[2020-12-29 14:32:49.357] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7474 }
[2020-12-29 14:32:49.359] [info] Neo4j @ 7687 is down. connect ECONNREFUSED 127.0.0.1:7687
[2020-12-29 14:32:49.383] [info] Neo4j @ 7474 is down. connect ECONNREFUSED 127.0.0.1:7474
[2020-12-29 14:32:50.493] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7687 }
[2020-12-29 14:32:50.517] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7474 }
[2020-12-29 14:32:50.518] [info] Neo4j @ 7687 is down. connect ECONNREFUSED 127.0.0.1:7687
[2020-12-29 14:32:50.543] [info] Neo4j @ 7474 is down. connect ECONNREFUSED 127.0.0.1:7474
[2020-12-29 14:32:51.627] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7687 }
[2020-12-29 14:32:51.628] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7474 }
[2020-12-29 14:32:51.629] [info] Neo4j @ 7474 is down. connect ECONNREFUSED 127.0.0.1:7474
[2020-12-29 14:32:51.701] [info] Neo4j @ 7687 is up and running!
[2020-12-29 14:32:52.716] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7687 }
[2020-12-29 14:32:52.717] [info] Check if neo4j is available on { host: '127.0.0.1', path: '/', port: 7474 }
[2020-12-29 14:32:52.721] [info] Neo4j @ 7687 is up and running!
[2020-12-29 14:32:52.823] [info] Neo4j @ 7474 is up and running!
[2020-12-29 14:32:56.061] [error] Graph-App 'Neo4j Browser' execution blocked: signature verification failure. {
  constructor: 'Error',
  stack: 'Error: Invalid content digest.\n' +
    '    at Object.exports.verifySignature (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:141:15)\n' +
    '    at Object.<anonymous> (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:27:36)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at /Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:7:71\n' +
    '    at new Promise (<anonymous>)\n' +
    '    at __awaiter (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:3:12)\n' +
    '    at Object.exports.verify (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/verify.js:17:31)\n' +
    '    at Object.<anonymous> (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/index.js:43:35)\n' +
    '    at Generator.next (<anonymous>)\n' +
    '    at fulfilled (/Applications/Neo4j Desktop.app/Contents/Resources/app.asar/node_modules/@neo4j/code-signer/lib/index.js:4:58)\n' +
    '    at runMicrotasks (<anonymous>)\n' +
    '    at processTicksAndRejections (internal/process/task_queues.js:85:5)'
}
[2020-12-29 14:33:16.826] [info] [1] Online check request: https://dist.neo4j.org/neo4j-desktop/win/latest.yml
[2020-12-29 14:33:17.411] [info] [1] Online check response: 200 version: 1.3.11
file

```
Reinstalling did not fix it either.

### Your Environment

macOS BigSur 11.1
Neo4j Desktop 1.3.11 (1.3.11.42)

**Comment by oskarhane** [comment]
Hi @luanne and sorry for the inconvenience. 
This can happen is files change within signed graph apps.

Desktop does however auto-install missing graph apps on startup so what you can do is to delete the `~/Library/Application Support/Neo4j Desktop/Application/graphApps/_global/neo4j-browser` folder and restart Neo4j Desktop.
That should fox it.
In a coming version of Desktop we will have something in the UI to help you re-install broken graph apps.

**Comment by luanne** [comment]
That fixed it, thanks @oskarhane!
