### ISSUE TITLE
dbms.logs.debug.level=DEBUG causes SSL error on netty library load unless DISABLED bolt.tls_level is set

### ISSUE THREAD

**Issue by obrienlabs** [neo4j/neo4j-browser#343]
I did run into an issue with SSL creation during OPTIONAL (the default) only when a certain logging parameter was set to DEBUG - I'll raise a separate issue on this.
The fix was to set tls_level on the indexed 0 bolt property not directly on bolt.tls_level

```
      <entry key="dbms.connector.bolt.tls_level" value="DISABLED" /> <!--  no effect - missing index 0 -->
        <entry key="dbms.logs.debug.level" value="DEBUG"/
causes

java.lang.IllegalArgumentException: Failed to load any of the given libraries: [netty-tcnative-osx-x86_64, netty-tcnative]
	at io.netty.util.internal.NativeLibraryLoader.loadFirstAvailable(NativeLibraryLoader.java:173)
	at io.netty.handler.ssl.OpenSsl.loadTcNative(OpenSsl.java:380)
	at io.netty.handler.ssl.OpenSsl.<clinit>(OpenSsl.java:99)
	at io.netty.handler.ssl.SslContext.defaultProvider(SslContext.java:117)
	at io.netty.handler.ssl.SslContext.defaultServerProvider(SslContext.java:104)
	at io.netty.handler.ssl.SslContext.newServerContextInternal(SslContext.java:404)
	at io.netty.handler.ssl.SslContextBuilder.build(SslContextBuilder.java:402)
	at org.neo4j.bolt.BoltKernelExtension.createSslContext(BoltKernelExtension.java:224)
	at org.neo4j.bolt.BoltKernelExtension.lambda$newInstance$0(BoltKernelExtension.java:182)

fixed with
                    config.put( bolt.encryption_level.name(), "DISABLED" );
which renders in jconsole as 
dbms.connector.0.bolt.tls_level

**Comment by pe4cey** [comment]
This issue was moved to neo4j/neo4j#8528
