### ISSUE TITLE
yarn test fails at "standard --fix"

### ISSUE THREAD

**Issue by naisanza** [neo4j/neo4j-browser#418]
I don't know what I'm doing here. But after installing `git`, `nodejs`, and `npm`, cloning the git repo, installing `yarn`, `standard`, `webpack-dashboard`, `lint`, `jest`, and running `yarn test`, the test fails

```
apt update
apt install -y git nodejs npm
ln -s /usr/bin/nodejs /usr/bin/node
git clone https://github.com/neo4j/neo4j-browser.git
cd neo4j-browser
npm install -g yarn
npm install -g standard
npm install -g webpack-dashboard
npm install -g lint
npm install -g jest
npm install -g
yarn test
```

yarn test error log:
```
root@neo4j-browser-test:~/neo4j-browser# yarn test
yarn test v0.22.0
$ npm run lint && jest 

> neo4j-browser@1.0.0 lint /root/neo4j-browser
> standard --fix

standard: Use JavaScript Standard Style (https://standardjs.com)
  /root/neo4j-browser/src/browser/modules/D3Visualization/components/Explorer.jsx:62:7: Unexpected literal in error position of callback.
  /root/neo4j-browser/src/browser/modules/D3Visualization/components/Explorer.jsx:69:7: Unexpected literal in error position of callback.
  /root/neo4j-browser/src/browser/modules/D3Visualization/components/Explorer.jsx:71:7: Unexpected literal in error position of callback.
  /root/neo4j-browser/src/browser/modules/Stream/Visualization.jsx:84:13: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/modules/commands/helpers/http.js:29:7: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/modules/commands/helpers/http.js:33:7: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/modules/commands/helpers/http.js:42:9: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/modules/commands/postConnectCmdEpic.test.js:60:48: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/modules/connections/connectionsDuck.js:298:70: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/modules/connections/connectionsDuck.js:305:31: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/modules/connections/connectionsDuck.js:307:44: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/modules/connections/connectionsDuck.test.js:32:1: Import in body of module; reorder to top.
  /root/neo4j-browser/src/shared/modules/favorites/favoritesDuck.js:33:1: Import in body of module; reorder to top.
  /root/neo4j-browser/src/shared/modules/favorites/foldersDuck.js:34:1: Import in body of module; reorder to top.
  /root/neo4j-browser/src/shared/services/bolt/bolt.js:90:7: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/services/bolt/bolt.js:105:7: Expected the Promise rejection reason to be an Error.
  /root/neo4j-browser/src/shared/services/bolt/boltMappings.test.js:128:7: Expected an assignment or function call and instead saw an expression.
  /root/neo4j-browser/src/shared/services/bolt/boltMappings.test.js:132:7: Expected an assignment or function call and instead saw an expression.
  /root/neo4j-browser/src/shared/services/bolt/boltMappings.test.js:165:7: Expected an assignment or function call and instead saw an expression.
  /root/neo4j-browser/src/shared/services/bolt/boltMappings.test.js:169:7: Expected an assignment or function call and instead saw an expression.
  /root/neo4j-browser/src/shared/services/bolt/boltMappings.test.js:246:7: Expected an assignment or function call and instead saw an expression.
  /root/neo4j-browser/src/shared/services/bolt/boltMappings.test.js:293:7: Expected an assignment or function call and instead saw an expression.

npm ERR! Linux 4.4.35-1-pve
npm ERR! argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lint"
npm ERR! node v4.2.6
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! neo4j-browser@1.0.0 lint: `standard --fix`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the neo4j-browser@1.0.0 lint script 'standard --fix'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the neo4j-browser package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     standard --fix
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs neo4j-browser
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls neo4j-browser
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/neo4j-browser/npm-debug.log
error Command failed with exit code 1.
```
npm-debug.log:

```
root@neo4j-browser-test:~/neo4j-browser# cat npm-debug.log
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/nodejs', '/usr/bin/npm', 'run', 'lint' ]
2 info using npm@3.5.2
3 info using node@v4.2.6
4 verbose run-script [ 'prelint', 'lint', 'postlint' ]
5 info lifecycle neo4j-browser@1.0.0~prelint: neo4j-browser@1.0.0
6 silly lifecycle neo4j-browser@1.0.0~prelint: no script for prelint, continuing
7 info lifecycle neo4j-browser@1.0.0~lint: neo4j-browser@1.0.0
8 verbose lifecycle neo4j-browser@1.0.0~lint: unsafe-perm in lifecycle true
9 verbose lifecycle neo4j-browser@1.0.0~lint: PATH: /usr/share/npm/bin/node-gyp-bin:/root/neo4j-browser/node_modules/.bin:/root/neo4j-browser/node_modules/.bin:/root/.config/yarn/link/node_modules/.bin:/root/neo4j-browser/node_modules/.bin:/root/.config/yarn/link/node_modules/.bin:/usr/local/lib/node_modules/yarn/bin/node-gyp-bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games
10 verbose lifecycle neo4j-browser@1.0.0~lint: CWD: /root/neo4j-browser
11 silly lifecycle neo4j-browser@1.0.0~lint: Args: [ '-c', 'standard --fix' ]
12 silly lifecycle neo4j-browser@1.0.0~lint: Returned: code: 1  signal: null
13 info lifecycle neo4j-browser@1.0.0~lint: Failed to exec lint script
14 verbose stack Error: neo4j-browser@1.0.0 lint: `standard --fix`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/share/npm/lib/utils/lifecycle.js:232:16)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at EventEmitter.emit (events.js:172:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/share/npm/lib/utils/spawn.js:24:14)
14 verbose stack     at emitTwo (events.js:87:13)
14 verbose stack     at ChildProcess.emit (events.js:172:7)
14 verbose stack     at maybeClose (internal/child_process.js:821:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
15 verbose pkgid neo4j-browser@1.0.0
16 verbose cwd /root/neo4j-browser
17 error Linux 4.4.35-1-pve
18 error argv "/usr/bin/nodejs" "/usr/bin/npm" "run" "lint"
19 error node v4.2.6
20 error npm  v3.5.2
21 error code ELIFECYCLE
22 error neo4j-browser@1.0.0 lint: `standard --fix`
22 error Exit status 1
23 error Failed at the neo4j-browser@1.0.0 lint script 'standard --fix'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the neo4j-browser package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     standard --fix
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs neo4j-browser
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls neo4j-browser
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

`yarn starts`:

```
root@neo4j-browser-test:~/neo4j-browser# yarn starts
yarn starts v0.22.0
$ webpack-dashboard -t 'Neo4j Browser' -- webpack-dev-server --https --colors --no-info 
Error: spawn webpack-dev-server ENOENT
    at exports._errnoException (util.js:870:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:178:32)
    at onErrorNT (internal/child_process.js:344:16)
    at nextTickCallbackWith2Args (node.js:441:9)
    at process._tickCallback (node.js:355:17)
    at Function.Module.runMain (module.js:444:11)
    at startup (node.js:136:18)
    at node.js:966:3
node.js:758
        throw new TypeError('invalid pid');
        ^

TypeError: invalid pid
    at process.kill (node.js:758:15)
    at process.<anonymous> (/usr/local/lib/node_modules/webpack-dashboard/bin/webpack-dashboard.js:79:13)
    at emitOne (events.js:82:20)
    at process.emit (events.js:169:7)
    at process.exit (node.js:749:17)
    at Immediate._onImmediate (/usr/local/lib/node_modules/webpack-dashboard/node_modules/blessed/lib/widgets/screen.js:221:15)
    at processImmediate [as _immediateCallback] (timers.js:383:17)
error Command failed with exit code 1.
```

**Comment by oskarhane** [comment]
Hi and thanks for the report!
The reason that happens is because of new rules added to the standard linter.
Try to uninstall the global standard version (you should be able to uninstall all the packages you installed globally except yarn) and execute `yarn install` to get the version of standard we're currently using.

We will align the code to the newest version of standard but haven't gotten around to it yet.

**Comment by naisanza** [comment]
@oskarhane oh perfect, I thought I was doing something wrong by the documentation

Thanks

**Comment by naisanza** [comment]
@oskarhane  How do I bind the listening address to `0.0.0.0`?

When `yarn start` runs, it listens on `0.0.0.0`, but only responds if host is `localhost`

Listening to 0.0.0.0:8080:

```
root@neo4j-browser-test:~# netstat -ant | grep LISTEN
tcp        0      0 0.0.0.0:5355            0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.53:53           0.0.0.0:*               LISTEN     
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN     
tcp        0      0 127.0.0.1:25            0.0.0.0:*               LISTEN     
tcp6       0      0 :::5355                 :::*                    LISTEN     
tcp6       0      0 :::9838                 :::*                    LISTEN     
tcp6       0      0 :::22                   :::*                    LISTEN     
tcp6       0      0 ::1:25                  :::*                    LISTEN
```

However, it returns the HTTP Response: 
```
Invalid Host header
```

wget on localhost:8080:
```
root@neo4j-browser-test:~# wget -O - localhost:8080
--2017-04-26 15:13:54--  http://localhost:8080/
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:8080... failed: Connection refused.
Connecting to localhost (localhost)|127.0.0.1|:8080... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2138 (2.1K) [text/html]
Saving to: 'STDOUT'

-                                   0%[                                                            ]       0  --.-KB/s               <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Neo4j Browser</title>
  <style>
    * {
        padding: 0;
        margin: 0;
    }
    html, body {
        width: 100%;
        height: 100%;
    }
  </style>
  <link rel="apple-touch-icon" sizes="57x57" href="assets/images/device-icons/apple-touch-icon-57x57.png">
  <link rel="apple-touch-icon" sizes="60x60" href="assets/images/device-icons/apple-touch-icon-60x60.png">
  <link rel="apple-touch-icon" sizes="72x72" href="assets/images/device-icons/apple-touch-icon-72x72.png">
  <link rel="apple-touch-icon" sizes="76x76" href="assets/images/device-icons/apple-touch-icon-76x76.png">
  <link rel="apple-touch-icon" sizes="114x114" href="assets/images/device-icons/apple-touch-icon-114x114.png">
  <link rel="apple-touch-icon" sizes="120x120" href="assets/images/device-icons/apple-touch-icon-120x120.png">
  <link rel="apple-touch-icon" sizes="144x144" href="assets/images/device-icons/apple-touch-icon-144x144.png">
  <link rel="apple-touch-icon" sizes="152x152" href="assets/images/device-icons/apple-touch-icon-152x152.png">
  <link rel="apple-touch-icon" sizes="180x180" href="assets/images/device-icons/apple-touch-icon-180x180.png">
  <link rel="icon" type="image/png" href="assets/images/device-icons/favicon-32x32.png" sizes="32x32">
  <link rel="icon" type="image/png" href="assets/images/device-icons/android-chrome-192x192.png" sizes="192x192">
  <link rel="icon" type="image/png" href="assets/images/device-icons/favicon-96x96.png" sizes="96x96">
  <link rel="icon" type="image/png" href="assets/images/device-icons/favicon-16x16.png" sizes="16x16">
  <link rel="manifest" href="assets/images/device-icons/manifest.json">
  <link rel="shortcut icon" href="assets/images/device-icons/favicon.ico">
  <script type="text/javascript" src="assets/js/neoPlanner.js"></script>
  <script type="text/javascript" src="assets/js/d3.min.js"></script>
</head>
<body>
  <div id="mount"></div>
<script type="text/javascript" src="vendor-6580cbae3570ef9bb565.js"></script><script type="text/javascript" src="app-6580cbae3570ef9bb565.js"></script></body>
</html>
-                                 100%[===========================================================>]   2.09K  --.-KB/s    in 0s      

2017-04-26 15:13:54 (226 MB/s) - written to stdout [2138/2138]
```

**Comment by oskarhane** [comment]
Hi,
What are you trying to accomplish?

The `yarn start` command is to start the development server.
If you want to serve the neo4j browser I would recommend you to first `yarn build` and then serve the static files in the `build/` directory with a more fitting webserver than the webpack development server.
Something like https://expressjs.com/

**Comment by naisanza** [comment]
@oskarhane I didn't know about `yarn build`, but yes! that would be it!
