### ISSUE TITLE
Neo4j browser (3.2.0) cannot run on window 10 (1703) machine.

### ISSUE THREAD

**Issue by yezuoxian** [neo4j/neo4j-browser#514]
It throw exception when I run yarn start.
```
yarn start v0.23.4
$ webpack-dashboard -t 'Neo4j Browser' -- webpack-dev-server --colors --no-info
┌─Log───────────────────────────────────────────────────────────────────── Error: spawn Browser' ENOENT
    at notFoundError (C:\Users\Tony\Documents\Workspace\Neo4j\neo4j-browser\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (C:\Users\Tony\Documents\Workspace\Neo4j\neo4j-browser\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (C:\Users\Tony\Documents\Workspace\Neo4j\neo4j-browser\node_modules\cross-spawn\lib\enoent.js:33:19)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
internal/process.js:190
      throw errnoException(err, 'kill');
      ^
Error: kill ESRCH
    at exports._errnoException (util.js:1018:11)
    at process.kill (internal/process.js:190:13)
    at process.<anonymous> (C:\Users\Tony\Documents\Workspace\Neo4j\neo4j-browser\node_modules\webpack-dashboard\bin\webpack-dashboard.js:79:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:164:15)
    at Immediate.<anonymous> (C:\Users\Tony\Documents\Workspace\Neo4j\neo4j-browser\node_modules\blessed\lib\widgets\screen.js:221:15)
    at runCallback (timers.js:666:20)
    at tryOnImmediate (timers.js:639:5)
    at processImmediate [as _immediateCallback] (timers.js:611:5)
error Command failed with exit code 1.
```

**Comment by kernelforce** [comment]
Also can not run on win7x64, throws the same errors.
yarn start v0.24.4
$ webpack-dashboard -t 'Neo4j Browser' -- webpack-dev-server --colors --no-info
Error: spawn Browser' ENOENT
    at notFoundError (e:\project\neo4j-browser-3.0\node_modules\cross-spawn\lib\enoent.js:11:11)
    at verifyENOENT (e:\project\neo4j-browser-3.0\node_modules\cross-spawn\lib\enoent.js:46:16)
    at ChildProcess.cp.emit (e:\project\neo4j-browser-3.0\node_modules\cross-spawn\lib\enoent.js:33:19
)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
internal/process.js:190
      throw errnoException(err, 'kill');
      ^

Error: kill ESRCH
    at exports._errnoException (util.js:1018:11)
    at process.kill (internal/process.js:190:13)
    at process.<anonymous> (e:\project\neo4j-browser-3.0\node_modules\webpack-dashboard\bin\webpack-da
shboard.js:79:13)
    at emitOne (events.js:101:20)
    at process.emit (events.js:188:7)
    at process.exit (internal/process.js:164:15)
    at Immediate.<anonymous> (e:\project\neo4j-browser-3.0\node_modules\blessed\lib\widgets\screen.js:
221:15)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
error Command failed with exit code 1.

**Comment by oskarhane** [comment]
Thanks for the report.
Is it the `webpack-dashboard` that fails?
Will it start if you manually type `./node_modules/.bin/webpack-dev-server --colors --no-info`?

**Comment by yezuoxian** [comment]
If I type `webpack-dev-server --colors --no-info` it will work properly.
I think is the `webpack-dashboard` that don't support windows?
Thanks for your reply.

**Comment by davidkhala** [comment]
Same problem occurs for me. Will there will a plan for compatibility patch? Or we can just wait for related dependencies update?

**Comment by yezuoxian** [comment]
The thing caused this problem is one of the dependence of the webpack-dashboard doesn't support the windows.
You can try to run this project by typing the command `./node_modules/.bin/webpack-dev-server --colors --no-info` and to see if it run properly.
The link of the webpack-dashboard:
[https://github.com/FormidableLabs/webpack-dashboard](webpack-dashboard)

**Comment by davidkhala** [comment]
题主北京人？我按 @oskarhane 他的提示跑通了的，就是想问开发团队有没有计划在webpack-dashboard支持windows之前率先支持windows。比如说做个中间件适配一下什么的

**Comment by yezuoxian** [comment]
在北京上学。应该是没有，你可以找找看~

**Comment by internetscooter** [comment]
This closed due to it being not a Neo4j issue? Can I suggest it be fixed to prevent others hitting the issue?

In package.json

```
"scripts": {
    "start": "webpack-dashboard -t 'Neo4j Browser' -- webpack-dev-server --colors --no-info",
    "starts": "webpack-dashboard -t 'Neo4j Browser' -- webpack-dev-server --https --colors --no-info",
    "startnodash": "webpack-dev-server --colors --no-info",
```

And in the Readme...

Development server
yarn start and point your web browser to http://localhost:8080 (Windows yarn startnodash)

Happy to submit a pull request if you think this is a good solution.

Note: I currently think the root cause is that webpack-dashboard spawns another process webpack-dev-server. The cross-spawn used doesn't like a process spawned from within a process (but will spawn a single process ok).
