### ISSUE TITLE
Neo4J browser keeps reconnecting and losing connection

### ISSUE THREAD

**Issue by nicolaschaillan** [neo4j/neo4j-browser#795]
Using neo4j latest Docker with Bolt and TLS REQUIRED hosted on Azure,

neo4j browser keeps losing connection and reconnect and most queries fail, I have to try them 2 or 3 times to get them to work.

This seems to be a critical issue... 

Also tried to connect to Neo4J browser sync but after auth on Google or LinkedIn, nothing happens, window closes and that is it. Still not authenticated.

Sending queries, keep getting: BoltConnectionError: No connection found, did you connect to Neo4j?

Using the following env: 
NEO4J_dbms_memory_pagecache_size=4G
NEO4J_dbms_connector_bolt_tls__level=REQUIRED
NEO4J_dbms_directories_import=/tmp_files
NEO4J_AUTH=neo4j/temp1024

Using two volumes ssl and data.

This was happening also without Docker so I doubt it is related.

I am getting tons of log errors:
2018-07-09 14:52:11.158+0000 WARN  Illegal character 0x16 in state=START for buffer HeapByteBuffer@e9c6d[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03\xD8`\xB0\xA"\x98...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-07-09 14:52:11.159+0000 WARN  Illegal character 0x16 in state=START for buffer HeapByteBuffer@4f72c66f[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03L)\x87e\xFc\x83h...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-07-09 14:52:11.992+0000 WARN  Illegal character 0x16 in state=START for buffer HeapByteBuffer@e9c6d[p=1,l=208,c=8192,r=207]={\x16<<<\x03\x01\x00\xCb\x01\x00\x00\xC7\x03\x03\xC5\xE2\x83S\x82\xC6\x0e...\x00\x08JJ\x00\x1d\x00\x17\x00\x18\xAa\xAa\x00\x01\x00>>>\x08http/1.1uP\x00\x00\x00\x0b\x00\x02...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-07-09 14:52:16.272+0000 WARN  Illegal character 0x16 in state=START for buffer HeapByteBuffer@e9c6d[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03\x91_'\x15\x18\xF4\x0f...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-07-09 14:52:16.635+0000 WARN  Illegal character 0x16 in state=START for buffer HeapByteBuffer@e9c6d[p=1,l=517,c=8192,r=516]={\x16<<<\x03\x01\x02\x00\x01\x00\x01\xFc\x03\x03\x80.\xB2\xCd\xFe\xF5\x19...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00>>>\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-07-09 14:52:17.033+0000 WARN  Illegal character 0x16 in state=START for buffer HeapByteBuffer@e9c6d[p=1,l=208,c=8192,r=207]={\x16<<<\x03\x01\x00\xCb\x01\x00\x00\xC7\x03\x03\x92\x93C+\xE6\x8b\x9c...\x00\x08**\x00\x1d\x00\x17\x00\x18\xCa\xCa\x00\x01\x00>>>\x08http/1.1uP\x00\x00\x00\x0b\x00\x02...\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00}
2018-07-09 14:53:41.433+0000 ERROR Unexpected error detected in bolt session '0242acfffe130002-0000000a-0000061e-b6fbd26feac9a55f-59135ee3'. The client is unauthorized due to authentication failure.
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: The client is unauthorized due to authentication failure.
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2018-07-09 15:46:06.430+0000 ERROR Unexpected error detected in bolt session '0242acfffe130002-0000000a-00000833-c140e25bde19a12d-f6a9aee1'. The client is unauthorized due to authentication failure.
org.neo4j.bolt.v1.runtime.BoltConnectionFatality: The client is unauthorized due to authentication failure.
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:742)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.handleFailure(BoltStateMachine.java:728)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.access$500(BoltStateMachine.java:62)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine$State$1.init(BoltStateMachine.java:435)
        at org.neo4j.bolt.v1.runtime.BoltStateMachine.init(BoltStateMachine.java:145)
        at org.neo4j.bolt.v1.messaging.BoltMessageRouter.lambda$onInit$0(BoltMessageRouter.java:70)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:195)
        at org.neo4j.bolt.runtime.DefaultBoltConnection.processNextBatch(DefaultBoltConnection.java:143)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.executeBatch(ExecutorBoltScheduler.java:170)
        at org.neo4j.bolt.runtime.ExecutorBoltScheduler.lambda$scheduleBatchOrHandleError$2(ExecutorBoltScheduler.java:153)
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)

**Comment by nicolaschaillan** [comment]
Neo4j Browser version: 3.1.14
Neo4j Server version: 3.4.1 (community)

Neo4J Browser Sync finally just connected but query connection issue remains.

**Comment by nicolaschaillan** [comment]
Also when I try to connect using http instead of bolt, I get a console error:
vendor-f283354f1f3addf2f0dc.js:1 WebSocket connection to 'ws://http:7687/' failed: Error in connection establishment: net::ERR_NAME_NOT_RESOLVED

This is on Chrome. Version 67.0.3396.99 (Official Build) (64-bit)

**Comment by oskarhane** [comment]
Hi and thanks for the report @nicolaschaillan!
Did you get this resolved?

**Comment by daveman1010221** [comment]
The issue persists.

**Comment by daveman1010221** [comment]
It seems to be the message that is the problem. Perhaps a really bad way of saying, "Your proxy settings at this moment seem to be affecting your browser's ability to communicate with our JavaScript library."
